spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/starcafe
    driver-class-name: org.mariadb.jdbc.Driver
    username: starcafe
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 9090